USE master
GO

CREATE DATABASE ozonTestDb
ON PRIMARY (
NAME = N'ozonTestDb',
FILENAME = N'e:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ozonTestDb.mdf',
SIZE = 8192 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 65536 KB
)
LOG ON (
NAME = N'ozonTestDb_log',
FILENAME = N'e:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ozonTestDb_log.ldf',
SIZE = 73728 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 65536 KB
)
GO

ALTER DATABASE ozonTestDb
SET
ANSI_NULL_DEFAULT OFF,
ANSI_NULLS OFF,
ANSI_PADDING OFF,
ANSI_WARNINGS OFF,
ARITHABORT OFF,
AUTO_CLOSE OFF,
AUTO_CREATE_STATISTICS ON,
AUTO_SHRINK OFF,
AUTO_UPDATE_STATISTICS ON,
AUTO_UPDATE_STATISTICS_ASYNC OFF,
COMPATIBILITY_LEVEL = 140,
CONCAT_NULL_YIELDS_NULL OFF,
CURSOR_CLOSE_ON_COMMIT OFF,
CURSOR_DEFAULT GLOBAL,
DATE_CORRELATION_OPTIMIZATION OFF,
DB_CHAINING OFF,
HONOR_BROKER_PRIORITY OFF,
MULTI_USER,
NESTED_TRIGGERS = ON,
NUMERIC_ROUNDABORT OFF,
PAGE_VERIFY CHECKSUM,
PARAMETERIZATION SIMPLE,
QUOTED_IDENTIFIER OFF,
READ_COMMITTED_SNAPSHOT OFF,
RECOVERY SIMPLE,
RECURSIVE_TRIGGERS OFF,
TRANSFORM_NOISE_WORDS = OFF,
TRUSTWORTHY OFF
WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE ozonTestDb
COLLATE Cyrillic_General_CI_AS
GO

ALTER DATABASE ozonTestDb
SET DISABLE_BROKER
GO

ALTER DATABASE ozonTestDb
SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE ozonTestDb
SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER DATABASE ozonTestDb
SET QUERY_STORE = OFF
GO

USE ozonTestDb
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER AUTHORIZATION ON DATABASE::ozonTestDb TO [home-ПК\home]
GO


USE ozonTestDb
GO

CREATE TABLE dbo.ExchangeRates (
  ExchangeRateId int IDENTITY,
  Amount int NOT NULL,
  CurrencyId int NOT NULL,
  Rate decimal(18, 3) NOT NULL,
  Date date NOT NULL,
  CreateDate datetime NOT NULL DEFAULT (getdate()),
  UpdateDate datetime NULL,
  CONSTRAINT PK_ExchangeRates PRIMARY KEY CLUSTERED (ExchangeRateId),
  CONSTRAINT KEY_ExchangeRates UNIQUE (CurrencyId, Date)
)
ON [PRIMARY]
GO